package com.example.localization

enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
    FRENCH("fr", "Français", "🇫🇷"),
    ENGLISH("en", "English", "🇬🇧"),
    SPANISH("es", "Español", "🇪🇸"),
    GERMAN("de", "Deutsch", "🇩🇪"),
    ARABIC("ar", "العربية", "🇸🇦"),
    PORTUGUESE("pt", "Português", "🇧🇷"),
    JAPANESE("ja", "日本語", "🇯🇵")
}

data class Strings(
    // App & Navigation
    val appTitle: String,
    val tabDashboard: String,
    val tabEditor: String,
    val tabSandbox: String,
    val tabAi: String,
    val tabScheduler: String,
    val tabBackup: String,
    val tabSettings: String,

    // Dashboard
    val activeAutomations: String,
    val totalRuns: String,
    val humanizationIndex: String,
    val batteryEfficiency: String,
    val quickStart: String,
    val newScript: String,
    val accessibilityStatus: String,
    val serviceActive: String,
    val serviceInactive: String,
    val grantService: String,
    val noRootNeeded: String,
    val recentScripts: String,
    val noScriptsYet: String,
    val noScriptsDesc: String,
    val runNow: String,
    val editScript: String,
    val deleteScript: String,
    val duplicateScript: String,

    // Editor & Actions
    val scriptName: String,
    val scriptDescription: String,
    val addAction: String,
    val step: String,
    val delayMs: String,
    val varianceMs: String,
    val jitterRadius: String,
    val actionTap: String,
    val actionDoubleTap: String,
    val actionLongPress: String,
    val actionSwipe: String,
    val actionWait: String,
    val actionOcrText: String,
    val actionImageMatch: String,
    val actionLoop: String,
    val conditionTarget: String,
    val conditionTextHint: String,
    val conditionTimeout: String,
    val fallbackAction: String,
    val saveScript: String,
    val scriptSaved: String,

    // Humanization / Anti-Detection
    val humanizeTitle: String,
    val humanizeDesc: String,
    val microJitter: String,
    val timeVariance: String,
    val naturalCurves: String,
    val antiBotSafeScore: String,
    val stealthMode: String,

    // Battery Optimizer
    val batteryTitle: String,
    val batteryMode: String,
    val modeEco: String,
    val modeBalanced: String,
    val modeTurbo: String,
    val amoledPureBlack: String,
    val autoPauseLowBattery: String,
    val screenDimming: String,

    // Sandbox & Floating Controller
    val sandboxTitle: String,
    val sandboxSubtitle: String,
    val startSimulation: String,
    val stopSimulation: String,
    val pauseSimulation: String,
    val resumeSimulation: String,
    val addTargetPin: String,
    val clearPins: String,
    val simulatedScreen: String,
    val ocrRecognizedText: String,
    val triggerDetected: String,
    val liveConsole: String,
    val clearLogs: String,

    // AI Assistant
    val aiTitle: String,
    val aiPromptHint: String,
    val generateScriptWithAi: String,
    val aiGenerating: String,
    val aiTemplates: String,
    val templateGameFarming: String,
    val templateDailyCheckin: String,
    val templateSocialScroll: String,
    val templateOcrClaim: String,
    val aiOptimizeScript: String,
    val aiOptimizeDesc: String,
    val aiScoreFeedback: String,

    // Scheduler
    val schedulerTitle: String,
    val newSchedule: String,
    val scheduleTime: String,
    val repeatDays: String,
    val countdownTimer: String,
    val startInMinutes: String,
    val scheduledScripts: String,
    val noSchedules: String,

    // Backup & Cloud & Local Phone Storage
    val backupTitle: String,
    val cloudAutoBackup: String,
    val cloudBackupTitle: String = cloudAutoBackup,
    val cloudBackupDesc: String,
    val lastBackup: String,
    val createBackupNow: String,
    val exportJson: String,
    val exportConfig: String = exportJson,
    val importJson: String,
    val importConfig: String = importJson,
    val restoreSnapshot: String,
    val backupSuccess: String,
    val backupRestored: String,
    val cloudSynced: String,
    val localPhoneBackup: String = "Sauvegarde Locale sur le Téléphone",
    val localPhoneBackupDesc: String = "Sauvegardez vos configurations d'automatisation directement dans la mémoire du téléphone.",
    val saveToPhoneBtn: String = "Sauvegarder sur le téléphone",
    val restoreFromPhoneBtn: String = "Restaurer depuis le téléphone",
    val localFilesTitle: String = "Fichiers locaux enregistrés",
    val deleteLocalBackup: String = "Supprimer le fichier",

    // Visual Recorder
    val visualRecorder: String = "Enregistreur de Script Visuel",
    val startVisualRecording: String = "Démarrer l'enregistrement",
    val stopVisualRecording: String = "Terminer & Convertir",
    val recordingInProgress: String = "Enregistrement en direct",
    val recordedActionsCount: String = "Actions capturées",
    val recordTapMode: String = "Clic",
    val recordSwipeMode: String = "Glissement",
    val recordTextMode: String = "Saisie Texte",
    val convertRecordingTitle: String = "Convertir l'enregistrement en Script",
    val actionTextInput: String = "Saisie de Texte",
    val inputTextLabel: String = "Texte à saisir",

    // AI Analysis
    val aiAnalyzeScriptTitle: String = "Analyse & Optimisation de Scripts",
    val aiScoreBefore: String = "Score Anti-Bot Initial",
    val aiScoreAfter: String = "Score Optimisé IA",
    val aiBatteryGain: String = "Gain Énergie Batterie",
    val applyAiOptimizations: String = "Appliquer l'Optimisation IA",

    // Settings
    val settingsTitle: String,
    val language: String,
    val selectLanguage: String = language,
    val pointerStyle: String,
    val hapticFeedback: String,
    val audioClickFeedback: String,
    val floatingWidgetEnabled: String,
    val aboutApp: String,
    val version: String,
    val rootlessEngine: String
)

object LocalizationProvider {
    val french = Strings(
        appTitle = "AutoClicker AI",
        tabDashboard = "Accueil",
        tabEditor = "Éditeur",
        tabSandbox = "Bac à sable",
        tabAi = "Assistant IA",
        tabScheduler = "Planning",
        tabBackup = "Sauvegarde",
        tabSettings = "Paramètres",

        activeAutomations = "Automatisations",
        totalRuns = "Exécutions",
        humanizationIndex = "Indice Anti-Bot",
        batteryEfficiency = "Économie Batterie",
        quickStart = "Démarrage Rapide",
        newScript = "Nouveau Script",
        accessibilityStatus = "Service d'Accessibilité",
        serviceActive = "Actif & Prêt",
        serviceInactive = "Désactivé (Requis)",
        grantService = "Activer sans Root",
        noRootNeeded = "100% Sans Root • Android 7 à 15+",
        recentScripts = "Mes Scripts & Macros",
        noScriptsYet = "Aucun script créé",
        noScriptsDesc = "Créez votre première automatisation ou utilisez l'IA pour générer un script en quelques secondes.",
        runNow = "Lancer",
        editScript = "Modifier",
        deleteScript = "Supprimer",
        duplicateScript = "Dupliquer",

        scriptName = "Nom du script",
        scriptDescription = "Description / Objectif",
        addAction = "Ajouter une Action",
        step = "Étape",
        delayMs = "Délai (ms)",
        varianceMs = "Variation aléatoire (ms)",
        jitterRadius = "Rayon de micro-décalage (px)",
        actionTap = "Clic Simple",
        actionDoubleTap = "Double Clic",
        actionLongPress = "Appui Long",
        actionSwipe = "Glissement / Swipe",
        actionWait = "Pause / Attente",
        actionOcrText = "Condition Texte (OCR)",
        actionImageMatch = "Reconnaissance Image",
        actionLoop = "Boucle / Répétition",
        conditionTarget = "Texte ou Image cible",
        conditionTextHint = "Ex: 'Réclamer', 'Suivant', 'Accepter'",
        conditionTimeout = "Délai max de détection",
        fallbackAction = "Action si non trouvé",
        saveScript = "Enregistrer le script",
        scriptSaved = "Script enregistré avec succès !",

        humanizeTitle = "Mode Humain & Anti-Détection",
        humanizeDesc = "Génère des micro-variations de position (jitter) et de timing pour simuler un doigt humain réel et contourner les systèmes anti-bot.",
        microJitter = "Micro-décalage spatial (±px)",
        timeVariance = "Variation du rythme (±ms)",
        naturalCurves = "Courbes de swipe de Bézier naturelles",
        antiBotSafeScore = "Score de sécurité anti-détection",
        stealthMode = "Mode Furtif Haute Sécurité",

        batteryTitle = "Optimisation de la Batterie",
        batteryMode = "Profil Énergétique",
        modeEco = "Éco (Faible Conso & Fréquence)",
        modeBalanced = "Équilibré (Standard)",
        modeTurbo = "Ultra-Rapide (Haute Précision)",
        amoledPureBlack = "Thème Noir AMOLED Économique",
        autoPauseLowBattery = "Pause auto si batterie < 15%",
        screenDimming = "Atténuation de l'écran pendant l'exécution",

        sandboxTitle = "Testeur Interactif & Overlay",
        sandboxSubtitle = "Testez vos points de clic et la reconnaissance de texte OCR en direct sur écran simulé.",
        startSimulation = "Démarrer Test",
        stopSimulation = "Arrêter",
        pauseSimulation = "Pause",
        resumeSimulation = "Reprendre",
        addTargetPin = "+ Point Cible",
        clearPins = "Effacer",
        simulatedScreen = "Écran de Simulation",
        ocrRecognizedText = "Texte OCR Détecté",
        triggerDetected = "Condition Déclenchée !",
        liveConsole = "Journal d'Exécution en Direct",
        clearLogs = "Effacer logs",

        aiTitle = "Générateur & Optimiseur IA",
        aiPromptHint = "Décrivez ce que vous souhaitez automatiser en français...\nEx: 'Clique toutes les 3s sur le bouton Réclamer, puis glisse vers le haut et répète 10 fois'",
        generateScriptWithAi = "Générer avec Gemini IA",
        aiGenerating = "Génération de l'automatisation en cours...",
        aiTemplates = "Modèles d'automatisation populaires",
        templateGameFarming = "Farming automatique de jeu",
        templateDailyCheckin = "Récompenses quotidiennes",
        templateSocialScroll = "Défilement & Like continu",
        templateOcrClaim = "Détection intelligente de texte OCR",
        aiOptimizeScript = "Optimiser & Humaniser le Script",
        aiOptimizeDesc = "L'IA analyse vos délais et mouvements pour éliminer les patterns robotiques détectables.",
        aiScoreFeedback = "Analyse Anti-Bot par l'IA",

        schedulerTitle = "Planification Automatique",
        newSchedule = "Nouvelle Planification",
        scheduleTime = "Heure de déclenchement",
        repeatDays = "Jours de répétition",
        countdownTimer = "Minuteur à rebours",
        startInMinutes = "Lancer dans (minutes)",
        scheduledScripts = "Tâches Planifiées",
        noSchedules = "Aucune tâche planifiée actuellement.",

        backupTitle = "Sauvegarde & Cloud Sync",
        cloudAutoBackup = "Sauvegarde Cloud Automatique",
        cloudBackupDesc = "Vos scripts sont synchronisés en temps réel et peuvent être exportés ou restaurés à tout moment.",
        lastBackup = "Dernière synchro",
        createBackupNow = "Sauvegarder Maintenant",
        exportJson = "Exporter au format JSON",
        importJson = "Importer un script JSON",
        restoreSnapshot = "Restaurer un point de sauvegarde",
        backupSuccess = "Sauvegarde cloud effectuée avec succès !",
        backupRestored = "Sauvegarde restaurée !",
        cloudSynced = "Synchronisé avec le cloud sécurisé",

        settingsTitle = "Paramètres & Personnalisation",
        language = "Langue de l'application",
        selectLanguage = "Choisir la langue",
        pointerStyle = "Style et taille du curseur cible",
        hapticFeedback = "Vibration au clic",
        audioClickFeedback = "Son au clic",
        floatingWidgetEnabled = "Widget flottant par-dessus les applications",
        aboutApp = "À propos de l'Auto Clicker",
        version = "Version 1.0.0 • Architecture Moderne",
        rootlessEngine = "Moteur d'Accessibilité Sans Root Android"
    )

    val english = Strings(
        appTitle = "AutoClicker AI",
        tabDashboard = "Home",
        tabEditor = "Editor",
        tabSandbox = "Sandbox",
        tabAi = "AI Assistant",
        tabScheduler = "Schedule",
        tabBackup = "Backup",
        tabSettings = "Settings",

        activeAutomations = "Automations",
        totalRuns = "Total Executions",
        humanizationIndex = "Anti-Bot Rating",
        batteryEfficiency = "Battery Saver",
        quickStart = "Quick Start",
        newScript = "New Script",
        accessibilityStatus = "Accessibility Service",
        serviceActive = "Active & Ready",
        serviceInactive = "Disabled (Required)",
        grantService = "Enable without Root",
        noRootNeeded = "100% No Root Required • Android 7 to 15+",
        recentScripts = "My Automation Scripts",
        noScriptsYet = "No scripts created yet",
        noScriptsDesc = "Create your first automation or let Gemini AI generate one for you in seconds.",
        runNow = "Run",
        editScript = "Edit",
        deleteScript = "Delete",
        duplicateScript = "Duplicate",

        scriptName = "Script Name",
        scriptDescription = "Description / Goal",
        addAction = "Add Action Step",
        step = "Step",
        delayMs = "Delay (ms)",
        varianceMs = "Random Variance (ms)",
        jitterRadius = "Micro-jitter Radius (px)",
        actionTap = "Single Tap",
        actionDoubleTap = "Double Tap",
        actionLongPress = "Long Press",
        actionSwipe = "Natural Swipe",
        actionWait = "Wait / Pause",
        actionOcrText = "OCR Text Trigger",
        actionImageMatch = "Image Pattern Match",
        actionLoop = "Loop Block",
        conditionTarget = "Target Text or Pattern",
        conditionTextHint = "e.g. 'Claim', 'Next', 'Accept', 'Reward'",
        conditionTimeout = "Detection Timeout",
        fallbackAction = "Fallback if not found",
        saveScript = "Save Script",
        scriptSaved = "Script saved successfully!",

        humanizeTitle = "Human Touch & Anti-Detection",
        humanizeDesc = "Applies Gaussian spatial jitter and random delay variance to emulate genuine human fingertip gestures.",
        microJitter = "Spatial micro-jitter (±px)",
        timeVariance = "Timing rhythm variance (±ms)",
        naturalCurves = "Natural Bezier swipe curves",
        antiBotSafeScore = "Anti-Bot Safety Rating",
        stealthMode = "High Security Stealth Mode",

        batteryTitle = "Battery Optimizer",
        batteryMode = "Power Profile",
        modeEco = "Eco (Low Power & Throttle)",
        modeBalanced = "Balanced (Standard)",
        modeTurbo = "Ultra-Fast (High Precision)",
        amoledPureBlack = "AMOLED Pure Black Theme",
        autoPauseLowBattery = "Auto-pause when battery < 15%",
        screenDimming = "Dim screen during execution",

        sandboxTitle = "Interactive Sandbox & Overlay",
        sandboxSubtitle = "Test tap positions, swipe vectors, and OCR text detection on a live interactive preview canvas.",
        startSimulation = "Start Test",
        stopSimulation = "Stop",
        pauseSimulation = "Pause",
        resumeSimulation = "Resume",
        addTargetPin = "+ Add Pin",
        clearPins = "Clear",
        simulatedScreen = "Simulation Screen",
        ocrRecognizedText = "Detected OCR Text",
        triggerDetected = "Condition Triggered!",
        liveConsole = "Live Execution Log",
        clearLogs = "Clear Logs",

        aiTitle = "AI Script Generator & Optimizer",
        aiPromptHint = "Describe what you want to automate...\ne.g. 'Click the Claim button every 2 seconds, wait for Next to appear, then swipe up and loop 20 times'",
        generateScriptWithAi = "Generate with Gemini AI",
        aiGenerating = "Generating smart automation...",
        aiTemplates = "Popular Automation Templates",
        templateGameFarming = "Game Auto-Farming Loop",
        templateDailyCheckin = "Daily Reward Auto-Collector",
        templateSocialScroll = "Social Feed Scroller & Liker",
        templateOcrClaim = "Smart OCR Text Hunter",
        aiOptimizeScript = "Optimize & Humanize Script",
        aiOptimizeDesc = "AI inspects delays and coordinates to eliminate robotic signatures.",
        aiScoreFeedback = "AI Anti-Bot Inspection",

        schedulerTitle = "Task Scheduler",
        newSchedule = "New Schedule",
        scheduleTime = "Trigger Time",
        repeatDays = "Repeat Days",
        countdownTimer = "Countdown Timer",
        startInMinutes = "Start in (minutes)",
        scheduledScripts = "Scheduled Tasks",
        noSchedules = "No scheduled tasks yet.",

        backupTitle = "Cloud Backup & Sync",
        cloudAutoBackup = "Automatic Cloud Backup",
        cloudBackupDesc = "Your automations are synced safely to cloud and can be exported/restored anytime.",
        lastBackup = "Last Synced",
        createBackupNow = "Backup Now",
        exportJson = "Export as JSON",
        importJson = "Import JSON Script",
        restoreSnapshot = "Restore Backup Snapshot",
        backupSuccess = "Cloud backup completed successfully!",
        backupRestored = "Backup restored successfully!",
        cloudSynced = "Synced with secure cloud",

        settingsTitle = "Settings & Customization",
        language = "App Language",
        selectLanguage = "Select Language",
        pointerStyle = "Target Pin Style & Size",
        hapticFeedback = "Vibrate on click",
        audioClickFeedback = "Audio click feedback",
        floatingWidgetEnabled = "Floating controller overlay over apps",
        aboutApp = "About AutoClicker AI",
        version = "Version 1.0.0 • Modern Architecture",
        rootlessEngine = "Rootless Android Accessibility Engine"
    )

    val spanish = english.copy(
        appTitle = "AutoClicker AI",
        tabDashboard = "Inicio",
        tabEditor = "Editor",
        tabSandbox = "Pruebas",
        tabAi = "Asistente IA",
        tabScheduler = "Programador",
        tabBackup = "Copia Cloud",
        tabSettings = "Ajustes",
        activeAutomations = "Automatizaciones",
        quickStart = "Inicio Rápido",
        newScript = "Nuevo Script",
        accessibilityStatus = "Servicio de Accesibilidad",
        serviceActive = "Activo y Listo",
        serviceInactive = "Desactivado (Requerido)",
        grantService = "Activar sin Root",
        noRootNeeded = "100% Sin Root • Android 7 a 15+",
        runNow = "Ejecutar",
        editScript = "Editar",
        deleteScript = "Eliminar",
        duplicateScript = "Duplicar",
        addAction = "Añadir Acción",
        saveScript = "Guardar Script",
        scriptSaved = "¡Script guardado con éxito!",
        humanizeTitle = "Modo Humano y Anti-Detección",
        batteryTitle = "Optimización de Batería",
        language = "Idioma de la Aplicación",
        generateScriptWithAi = "Generar con Gemini IA"
    )

    val german = english.copy(
        appTitle = "AutoClicker AI",
        tabDashboard = "Startseite",
        tabEditor = "Editor",
        tabSandbox = "Sandbox",
        tabAi = "KI-Assistent",
        tabScheduler = "Zeitplan",
        tabBackup = "Backup",
        tabSettings = "Einstellungen",
        activeAutomations = "Automatisierungen",
        quickStart = "Schnellstart",
        newScript = "Neues Skript",
        accessibilityStatus = "Bedienungshilfen-Dienst",
        serviceActive = "Aktiv & Bereit",
        serviceInactive = "Deaktiviert (Erforderlich)",
        grantService = "Ohne Root aktivieren",
        runNow = "Starten",
        saveScript = "Skript speichern",
        scriptSaved = "Skript erfolgreich gespeichert!",
        language = "App-Sprache",
        generateScriptWithAi = "Mit Gemini KI generieren"
    )

    val arabic = english.copy(
        appTitle = "AutoClicker AI",
        tabDashboard = "الرئيسية",
        tabEditor = "المحرر",
        tabSandbox = "بيئة الاختبار",
        tabAi = "المساعد الذكي",
        tabScheduler = "الجدولة",
        tabBackup = "النسخ الاحتياطي",
        tabSettings = "الإعدادات",
        activeAutomations = "المهام التلقائية",
        quickStart = "تشغيل سريع",
        newScript = "سيناريو جديد",
        accessibilityStatus = "خدمة إمكانية الوصول",
        serviceActive = "مفعل وجاهز",
        serviceInactive = "معطل (مطلوب)",
        grantService = "تفعيل بدون روت",
        noRootNeeded = "بدون روت 100% • أندرويد 7 إلى 15+",
        runNow = "تشغيل",
        saveScript = "حفظ السيناريو",
        scriptSaved = "تم حفظ السيناريو بنجاح!",
        language = "لغة التطبيق",
        generateScriptWithAi = "إنشاء باستخدام الذكاء الاصطناعي"
    )

    val portuguese = english.copy(
        appTitle = "AutoClicker AI",
        tabDashboard = "Início",
        tabEditor = "Editor",
        tabSandbox = "Ambiente de Teste",
        tabAi = "Assistente IA",
        tabScheduler = "Agendamento",
        tabBackup = "Backup Nuvem",
        tabSettings = "Configurações",
        activeAutomations = "Automações",
        quickStart = "Início Rápido",
        newScript = "Novo Script",
        grantService = "Ativar sem Root",
        runNow = "Executar",
        saveScript = "Salvar Script",
        language = "Idioma do Aplicativo",
        generateScriptWithAi = "Gerar com Gemini IA"
    )

    val japanese = english.copy(
        appTitle = "AutoClicker AI",
        tabDashboard = "ホーム",
        tabEditor = "エディタ",
        tabSandbox = "テスト環境",
        tabAi = "AIアシスタント",
        tabScheduler = "スケジュール",
        tabBackup = "クラウドバックアップ",
        tabSettings = "設定",
        activeAutomations = "自動化スクリプト",
        quickStart = "クイックスタート",
        newScript = "新規スクリプト",
        grantService = "Root化不要で有効化",
        runNow = "実行",
        saveScript = "スクリプトを保存",
        language = "アプリ言語",
        generateScriptWithAi = "Gemini AIで生成"
    )

    fun getStrings(language: AppLanguage): Strings = when (language) {
        AppLanguage.FRENCH -> french
        AppLanguage.ENGLISH -> english
        AppLanguage.SPANISH -> spanish
        AppLanguage.GERMAN -> german
        AppLanguage.ARABIC -> arabic
        AppLanguage.PORTUGUESE -> portuguese
        AppLanguage.JAPANESE -> japanese
    }
}
